
include("abstractplans.jl")
include("interactionlists.jl")
include("translateplanbuilder.jl")
include("storednodeplanbuilder.jl")
include("aggregation/aggregate.jl")
include("aggregation/aggregatetranslate.jl")
include("disaggregation/disaggregate.jl")
include("disaggregation/disaggregatetranslate.jl")
include("split.jl")
include("galerkinplans.jl")
include("petrovplans.jl")
include("planbuilders.jl")
include("adjointplans.jl")
include("checkadmissibility.jl")
